# Generated by Django 5.1.3 on 2024-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
