# Generated by Django 5.1.3 on 2024-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0003_remove_livro_capa_livrocapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(verbose_name=''),
        ),
    ]
